---
name: ruby-tests

on:
  pull_request_target:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    name: Tests with Ruby ${{ matrix.ruby }} and ${{ matrix.gemfile }}
    runs-on: "ubuntu-latest"
    if: |
      github.actor == 'dependabot[bot]' && github.event_name == 'pull_request_target' ||
      github.actor != 'dependabot[bot]'
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7", "3.0", "3.1"]
        gemfile:
          - Gemfile
          - gemfiles/7_0.gemfile
          - gemfiles/6_1.gemfile
          - gemfiles/6_0.gemfile
    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options:
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2.4.0

      - uses: actions/cache@v3.0.5
        with:
          path: vendor/bundle
          key: >
            ${{ runner.os }}-${{ matrix.ruby }}-gems-${{
            hashFiles(matrix.gemfile) }}

      - name: Install PostgreSQL 11 client
        run: |
          sudo apt -y install libpq-dev

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install gem dependencies
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle update --jobs 4 --retry 3

      - name: Run Tests
        env:
          PGHOST: localhost
          PGUSER: postgres
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
        run: |
          psql -U postgres -c "create database test"
          bundle exec rake
