---
name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Tests with Ruby ${{ matrix.ruby }} and ${{ matrix.gemfile }}
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.6.x, 2.7.x, 3.0.x]
        gemfile:
          - Gemfile
          - gemfiles/6_0.gemfile
          - gemfiles/5_2.gemfile
          - gemfiles/5_1.gemfile
          - gemfiles/5_0.gemfile

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options:
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/cache@v2.1.5
        with:
          path: vendor/bundle
          key: >
            ${{ runner.os }}-${{ matrix.ruby }}-gems-${{
            hashFiles(matrix.gemfile) }}
          restore-keys: >
            ${{ runner.os }}-${{ matrix.ruby }}-gems-${{
            hashFiles(matrix.gemfile) }}

      - name: Set up Ruby
        uses: actions/setup-ruby@v1.1.3
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install PostgreSQL client
        env:
          PGHOST: localhost
          PGUSER: postgres
        run: |
          sudo apt-get -yqq install libpq-dev
          psql -U postgres -c "create database test"

      - name: Install gem dependencies
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle update --jobs 4 --retry 3

      - name: Run Tests
        env:
          PGHOST: localhost
          PGUSER: postgres
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
        run: |
          bundle exec rake
